language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO=Django==1.8.2
  - DJANGO=Django==1.7.8
  - DJANGO=Django==1.6.5

install:
  - pip install flake8 coverage coveralls $DJANGO
  - pip install -e .

script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark django_slowtests
  - coverage run setup.py test
  - coverage report

after_success: coveralls
